#!/usr/bin/env node
// Generated by `bun run build:skill` from scripts/docs.ts — do not edit.
// Regenerate and commit after changing anything under scripts/.
// @bun

// scripts/docs.ts
import { Buffer } from "buffer";
import { spawnSync } from "child_process";
import { createHash, randomUUID } from "crypto";
import { existsSync, lstatSync, lutimesSync, mkdirSync, mkdtempSync, readdirSync, readFileSync, readlinkSync, renameSync, rmSync, statSync, symlinkSync, writeFileSync } from "fs";
import { homedir } from "os";
import { basename, dirname, join as join2 } from "path";
import process from "process";

// scripts/lib/docs-cache.ts
import { join } from "node:path";
var DOCS_REPO = "pleaseai/spring-docs";
var CATALOG_URL = `https://raw.githubusercontent.com/${DOCS_REPO}/main/catalog.json`;
var DOCS_CACHE_SUBDIR = ".cache/pleaseai-spring/docs";
var SUPPORTED_CATALOG_VERSION = "1";
function lookupTag(catalog, project, version) {
  if (catalog.version !== SUPPORTED_CATALOG_VERSION)
    return { kind: "schema", found: catalog.version };
  const versions = catalog.projects[project];
  if (!versions)
    return { kind: "unknown-project", project, known: Object.keys(catalog.projects).sort() };
  const entry = versions[version];
  if (!entry)
    return { kind: "unknown-version", project, version, known: Object.keys(versions) };
  if (entry.released_at === null)
    return { kind: "unpublished", project, version, tag: entry.tag };
  return { kind: "found", tag: entry.tag, releasedAt: entry.released_at };
}
function archiveName(project, version) {
  return `${project}-${version}.tar.gz`;
}
function archiveUrl(tag, project, version) {
  return `https://github.com/${DOCS_REPO}/releases/download/${tag}/${archiveName(project, version)}`;
}
function checksumUrl(tag, project, version) {
  return `${archiveUrl(tag, project, version)}.sha256`;
}
function isCatalog(value) {
  if (!isObjectMap(value))
    return false;
  if (typeof value.version !== "string")
    return false;
  const { projects } = value;
  if (!isObjectMap(projects))
    return false;
  return Object.values(projects).every(isVersionMap);
}
function isVersionMap(value) {
  if (!isObjectMap(value))
    return false;
  return Object.values(value).every((entry) => {
    if (!isObjectMap(entry))
      return false;
    if (typeof entry.tag !== "string")
      return false;
    return entry.released_at === null || typeof entry.released_at === "string";
  });
}
function isObjectMap(value) {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
var SAFE_SEGMENT_RE = /^[\w.+-]+$/;
function isSafeSegment(value) {
  if (value === "." || value === "..")
    return false;
  return SAFE_SEGMENT_RE.test(value);
}
function docsCachePath(cacheHome, tag) {
  return join(cacheHome, DOCS_CACHE_SUBDIR, tag);
}
var SHA256_LINE_RE = /^([0-9a-f]{64})\s+\*?(\S+)$/i;
function parseChecksum(contents, expectedName) {
  const line = contents.trim().split(`
`)[0]?.trim();
  if (!line)
    return;
  const match = SHA256_LINE_RE.exec(line);
  if (!match || !match[1] || !match[2])
    return;
  if (match[2] !== expectedName)
    return;
  return match[1].toLowerCase();
}
function summarizeCatalog(catalog, project) {
  if (catalog.version !== SUPPORTED_CATALOG_VERSION)
    return { kind: "schema", found: catalog.version };
  const names = Object.keys(catalog.projects).sort(compareCodePoints);
  if (project !== undefined && !names.includes(project))
    return { kind: "unknown-project", project, known: names };
  const wanted = project === undefined ? names : [project];
  return { kind: "coverage", projects: wanted.map((name) => coverageOf(catalog, name)) };
}
function coverageOf(catalog, project) {
  const versions = catalog.projects[project] ?? {};
  const published = [];
  const unpublished = [];
  for (const [version, entry] of Object.entries(versions))
    (entry.released_at === null ? unpublished : published).push(version);
  published.sort(compareVersions);
  unpublished.sort(compareVersions);
  return { project, published, unpublished };
}
function compareCodePoints(a, b) {
  if (a === b)
    return 0;
  return a < b ? -1 : 1;
}
var VERSION_CHUNK_RE = /\d+|\D+/g;
var DIGIT_CHUNK_RE = /^\d/;
function compareVersions(a, b) {
  const left = a.match(VERSION_CHUNK_RE) ?? [];
  const right = b.match(VERSION_CHUNK_RE) ?? [];
  for (let i = 0;i < Math.max(left.length, right.length); i++) {
    const x = left[i];
    const y = right[i];
    if (x === undefined)
      return -1;
    if (y === undefined)
      return 1;
    if (x === y)
      continue;
    const numeric = DIGIT_CHUNK_RE.test(x) && DIGIT_CHUNK_RE.test(y);
    if (numeric)
      return Number(x) - Number(y);
    return compareCodePoints(x, y);
  }
  return 0;
}

// scripts/docs.ts
var CACHE_HOME_ENV_OVERRIDE = "PLEASEAI_SPRING_CACHE_HOME";
function cacheHomeOf(explicit) {
  return explicit ?? process.env[CACHE_HOME_ENV_OVERRIDE] ?? homedir();
}
function pointerPath(cacheHome, project, version) {
  return `${docsCachePath(cacheHome, `${project}-${version}`)}.tag`;
}
function readPointer(cacheHome, project, version) {
  const path = pointerPath(cacheHome, project, version);
  if (!existsSync(path))
    return;
  const tag = readFileSync(path, "utf8").trim();
  if (!isSafeSegment(tag))
    return;
  return tag;
}
function writePointer(cacheHome, project, version, tag) {
  const path = pointerPath(cacheHome, project, version);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${tag}
`);
}
var INDEX_FILE = "_index.md";
function ready(project, version, tag, path, cached) {
  return { kind: "ready", project, version, tag, path, index: join2(path, INDEX_FILE), cached };
}
function unavailable(project, version, reason, suggestion) {
  return suggestion === undefined ? { kind: "unavailable", project, version, reason } : { kind: "unavailable", project, version, reason, suggestion };
}
async function fetchText(fetchImpl, url) {
  try {
    const response = await fetchImpl(url);
    if (!response.ok)
      return { error: `GET ${url} \u2192 ${response.status}` };
    return await response.text();
  } catch (err) {
    return { error: `GET ${url} failed: ${err instanceof Error ? err.message : String(err)}` };
  }
}
async function fetchCatalog(fetchImpl) {
  const text = await fetchText(fetchImpl, CATALOG_URL);
  if (typeof text !== "string")
    return { reason: text.error, suggestion: "check network access to raw.githubusercontent.com" };
  let parsed;
  try {
    parsed = JSON.parse(text);
  } catch (err) {
    return { reason: `catalog.json is not valid JSON: ${err instanceof Error ? err.message : String(err)}` };
  }
  if (!isCatalog(parsed))
    return { reason: "catalog.json does not have the expected shape", suggestion: "update the plugin" };
  return parsed;
}
function isUsableTree(path) {
  try {
    return statSync(join2(path, INDEX_FILE)).isFile();
  } catch {
    return false;
  }
}
function contentName(target, digest) {
  return `${basename(target)}.content-${digest.slice(0, 12)}-${randomUUID()}`;
}
function isDirectoryEntry(path) {
  try {
    return lstatSync(path).isDirectory();
  } catch {
    return false;
  }
}
function entryExists(path) {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}
function liveContent(target) {
  try {
    return basename(readlinkSync(target));
  } catch {
    return;
  }
}
var LINK_ATTEMPTS = 5;
function publish(extracted, target, digest) {
  const name = contentName(target, digest);
  const content = join2(dirname(target), name);
  const superseded = liveContent(target);
  renameSync(extracted, content);
  if (superseded !== undefined && superseded !== name)
    retire(join2(dirname(target), superseded));
  let outcome = "contended";
  for (let attempt = 0;attempt < LINK_ATTEMPTS && outcome === "contended"; attempt++)
    outcome = linkOnto(target, name);
  if (outcome !== "linked")
    swapOnto(content, target);
}
function retire(path) {
  const now = new Date;
  try {
    lutimesSync(path, now, now);
  } catch {}
}
function linkOnto(target, name) {
  const junction = process.platform === "win32";
  const staged = `${target}.link-${randomUUID()}`;
  try {
    symlinkSync(junction ? join2(dirname(target), name) : name, staged, junction ? "junction" : "dir");
  } catch {
    return "unsupported";
  }
  let displaced;
  try {
    if (junction ? entryExists(target) : isDirectoryEntry(target)) {
      displaced = `${target}.replaced-${randomUUID()}`;
      renameSync(target, displaced);
      retire(displaced);
    }
    renameSync(staged, target);
  } catch {
    if (displaced !== undefined && !entryExists(target)) {
      try {
        renameSync(displaced, target);
      } catch {}
    }
    discard(staged);
    return "contended";
  }
  return "linked";
}
function swapOnto(content, target) {
  const displaced = entryExists(target) ? `${target}.replaced-${randomUUID()}` : undefined;
  if (displaced !== undefined) {
    renameSync(target, displaced);
    retire(displaced);
  }
  try {
    renameSync(content, target);
  } catch (err) {
    if (displaced !== undefined && !entryExists(target))
      renameSync(displaced, target);
    throw err;
  }
}
function discard(path) {
  try {
    rmSync(path, { recursive: true, force: true });
  } catch {}
}
var LEFTOVER_TTL_MS = 60 * 60 * 1000;
var LEFTOVER_MARKERS = [".staging-", ".replaced-", ".link-", ".content-"];
function sweepLeftovers(target) {
  const parent = dirname(target);
  const prefix = basename(target);
  const live = liveContent(target);
  const cutoff = Date.now() - LEFTOVER_TTL_MS;
  let entries;
  try {
    entries = readdirSync(parent);
  } catch {
    return;
  }
  for (const name of entries) {
    if (!LEFTOVER_MARKERS.some((marker) => name.startsWith(`${prefix}${marker}`)))
      continue;
    if (name === live)
      continue;
    const path = join2(parent, name);
    try {
      if (lstatSync(path).mtimeMs < cutoff)
        rmSync(path, { recursive: true, force: true });
    } catch {}
  }
}
function unpack(archive, project, version, target, digest) {
  mkdirSync(dirname(target), { recursive: true });
  const staging = mkdtempSync(`${target}.staging-`);
  try {
    const archivePath = join2(staging, archiveName(project, version));
    writeFileSync(archivePath, archive);
    const result = spawnSync("tar", ["-xzf", archivePath, "-C", staging], { encoding: "utf8" });
    if (result.error)
      throw new Error(`could not run tar: ${result.error.message}`);
    if (result.status !== 0)
      throw new Error(`tar exited ${result.status}: ${(result.stderr ?? "").trim()}`);
    const extracted = join2(staging, `${project}-${version}`);
    if (!existsSync(extracted))
      throw new Error(`archive does not contain ${project}-${version}/`);
    if (!isUsableTree(extracted))
      throw new Error(`archive does not contain ${project}-${version}/${INDEX_FILE}`);
    publish(extracted, target, digest);
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}
async function resolveDocs(options) {
  const { project, version, refresh = false, noFetch = false } = options;
  const fetchImpl = options.fetchImpl ?? ((url) => fetch(url));
  const cacheHome = cacheHomeOf(options.cacheHome);
  if (!isSafeSegment(project) || !isSafeSegment(version)) {
    return unavailable(project, version, "project and version may contain only letters, digits, dot, plus, hyphen and underscore");
  }
  if (noFetch) {
    const tag = readPointer(cacheHome, project, version);
    const path = tag === undefined ? undefined : docsCachePath(cacheHome, tag);
    if (tag === undefined || path === undefined || !isUsableTree(path)) {
      return unavailable(project, version, `${project} ${version} is not in the local cache`, "drop --no-fetch to download it");
    }
    return ready(project, version, tag, path, true);
  }
  const fetched = await fetchCatalog(fetchImpl);
  if (!("projects" in fetched))
    return unavailable(project, version, fetched.reason, fetched.suggestion);
  const catalog = fetched;
  const lookup = lookupTag(catalog, project, version);
  switch (lookup.kind) {
    case "schema":
      return unavailable(project, version, `catalog.json is schema version ${lookup.found}, this plugin understands 1`, "update the plugin");
    case "unknown-project":
      return unavailable(project, version, `${DOCS_REPO} publishes no project "${project}"`, `known projects: ${lookup.known.join(", ") || "none"}`);
    case "unknown-version":
      return unavailable(project, version, `${DOCS_REPO} has not published ${project} ${version}`, `open an issue at https://github.com/${DOCS_REPO}/issues to have it built`);
    case "unpublished":
      return unavailable(project, version, `${DOCS_REPO} reserved ${lookup.tag} for ${project} ${version} but has published no archive under it`, `open an issue at https://github.com/${DOCS_REPO}/issues to have it built`);
  }
  const { tag } = lookup;
  if (!isSafeSegment(tag)) {
    return unavailable(project, version, `catalog.json maps ${project} ${version} to an unusable tag "${tag}"`, `report it at https://github.com/${DOCS_REPO}/issues`);
  }
  const target = docsCachePath(cacheHome, tag);
  sweepLeftovers(target);
  if (isUsableTree(target) && !refresh) {
    writePointer(cacheHome, project, version, tag);
    return ready(project, version, tag, target, true);
  }
  const checksumText = await fetchText(fetchImpl, checksumUrl(tag, project, version));
  if (typeof checksumText !== "string")
    return unavailable(project, version, checksumText.error);
  const expected = parseChecksum(checksumText, archiveName(project, version));
  if (expected === undefined) {
    return unavailable(project, version, `the checksum published for ${tag} does not describe ${archiveName(project, version)}`);
  }
  let archive;
  try {
    const response = await fetchImpl(archiveUrl(tag, project, version));
    if (!response.ok)
      return unavailable(project, version, `GET ${archiveUrl(tag, project, version)} \u2192 ${response.status}`);
    archive = Buffer.from(await response.arrayBuffer());
  } catch (err) {
    return unavailable(project, version, `downloading ${tag} failed: ${err instanceof Error ? err.message : String(err)}`);
  }
  const actual = createHash("sha256").update(archive).digest("hex");
  if (actual !== expected) {
    return unavailable(project, version, `checksum mismatch for ${tag}: expected ${expected.slice(0, 12)}\u2026, got ${actual.slice(0, 12)}\u2026`, "nothing was written to the cache; retry, and report it if it persists");
  }
  try {
    unpack(archive, project, version, target, actual);
  } catch (err) {
    return unavailable(project, version, `unpacking ${tag} failed: ${err instanceof Error ? err.message : String(err)}`);
  }
  writePointer(cacheHome, project, version, tag);
  return ready(project, version, tag, target, false);
}
async function listDocs(options = {}) {
  const fetchImpl = options.fetchImpl ?? ((url) => fetch(url));
  const { project } = options;
  const fetched = await fetchCatalog(fetchImpl);
  if (!("projects" in fetched))
    return { kind: "unavailable", ...fetched };
  const summary = summarizeCatalog(fetched, project);
  switch (summary.kind) {
    case "schema":
      return {
        kind: "unavailable",
        reason: `catalog.json is schema version ${summary.found}, this plugin understands 1`,
        suggestion: "update the plugin"
      };
    case "unknown-project":
      return {
        kind: "unavailable",
        reason: `${DOCS_REPO} publishes no project "${summary.project}"`,
        suggestion: `known projects: ${summary.known.join(", ") || "none"}`
      };
  }
  return { kind: "coverage", generatedAt: fetched.generated_at, projects: summary.projects };
}
var USAGE = [
  "usage: bun run scripts/docs.ts <project> <version> [--refresh] [--no-fetch]",
  "       bun run scripts/docs.ts --list [project]"
].join(`
`);
function parseArgs(argv) {
  const positional = [];
  let refresh = false;
  let noFetch = false;
  let list = false;
  for (const arg of argv) {
    if (arg === "--refresh")
      refresh = true;
    else if (arg === "--no-fetch")
      noFetch = true;
    else if (arg === "--list")
      list = true;
    else if (arg.startsWith("--"))
      return { error: `unknown argument: ${arg}` };
    else
      positional.push(arg);
  }
  return list ? parseList(positional, refresh || noFetch) : parseResolve(positional, refresh, noFetch);
}
function parseList(positional, cacheFlags) {
  if (cacheFlags)
    return { error: "--list takes no --refresh or --no-fetch" };
  const [project, ...extra] = positional;
  if (extra.length > 0)
    return { error: `unexpected argument: ${extra[0]}` };
  return project === undefined ? { mode: "list" } : { mode: "list", project };
}
function parseResolve(positional, refresh, noFetch) {
  const [project, version, ...extra] = positional;
  if (!project)
    return { error: "missing <project>" };
  if (!version)
    return { error: "missing <version>" };
  if (extra.length > 0)
    return { error: `unexpected argument: ${extra[0]}` };
  return { mode: "resolve", project, version, refresh, noFetch };
}
async function cli(argv) {
  const parsed = parseArgs(argv);
  if ("error" in parsed) {
    process.stderr.write(`${parsed.error}
${USAGE}
`);
    return 2;
  }
  let result;
  try {
    result = parsed.mode === "list" ? await listDocs(parsed) : await resolveDocs(parsed);
  } catch (err) {
    process.stderr.write(`${err instanceof Error ? err.stack ?? err.message : String(err)}
`);
    return 2;
  }
  process.stdout.write(`${JSON.stringify(result, null, 2)}
`);
  return result.kind === "unavailable" ? 1 : 0;
}
if (true) {
  const code = await cli(process.argv.slice(2));
  process.exit(code);
}
export {
  listDocs,
  parseArgs,
  resolveDocs
};
