#!/usr/bin/env node
// Generated by `bun run build:skill` from scripts/docs.ts — do not edit.
// Regenerate and commit after changing anything under scripts/.
// @bun

// scripts/docs.ts
import { Buffer } from "buffer";
import { spawnSync } from "child_process";
import { createHash } from "crypto";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, renameSync, rmSync, writeFileSync } from "fs";
import { homedir } from "os";
import { dirname, join as join2 } from "path";
import process from "process";

// scripts/lib/docs-cache.ts
import { join } from "node:path";
var DOCS_REPO = "pleaseai/spring-docs";
var CATALOG_URL = `https://raw.githubusercontent.com/${DOCS_REPO}/main/catalog.json`;
var DOCS_CACHE_SUBDIR = ".cache/pleaseai-spring/docs";
var SUPPORTED_CATALOG_VERSION = "1";
function lookupTag(catalog, project, version) {
  if (catalog.version !== SUPPORTED_CATALOG_VERSION)
    return { kind: "schema", found: catalog.version };
  const versions = catalog.projects[project];
  if (!versions)
    return { kind: "unknown-project", project, known: Object.keys(catalog.projects).sort() };
  const entry = versions[version];
  if (!entry)
    return { kind: "unknown-version", project, version, known: Object.keys(versions) };
  return { kind: "found", tag: entry.tag, releasedAt: entry.released_at };
}
function archiveName(project, version) {
  return `${project}-${version}.tar.gz`;
}
function archiveUrl(tag, project, version) {
  return `https://github.com/${DOCS_REPO}/releases/download/${tag}/${archiveName(project, version)}`;
}
function checksumUrl(tag, project, version) {
  return `${archiveUrl(tag, project, version)}.sha256`;
}
function docsCachePath(cacheHome, tag) {
  return join(cacheHome, DOCS_CACHE_SUBDIR, tag);
}
var SHA256_LINE_RE = /^([0-9a-f]{64})\s+\*?(\S+)$/i;
function parseChecksum(contents, expectedName) {
  const line = contents.trim().split(`
`)[0]?.trim();
  if (!line)
    return;
  const match = SHA256_LINE_RE.exec(line);
  if (!match || !match[1] || !match[2])
    return;
  if (match[2] !== expectedName)
    return;
  return match[1].toLowerCase();
}

// scripts/docs.ts
var CACHE_HOME_ENV_OVERRIDE = "PLEASEAI_SPRING_CACHE_HOME";
function cacheHomeOf(explicit) {
  return explicit ?? process.env[CACHE_HOME_ENV_OVERRIDE] ?? homedir();
}
function pointerPath(cacheHome, project, version) {
  return `${docsCachePath(cacheHome, `${project}-${version}`)}.tag`;
}
function readPointer(cacheHome, project, version) {
  const path = pointerPath(cacheHome, project, version);
  if (!existsSync(path))
    return;
  const tag = readFileSync(path, "utf8").trim();
  return tag === "" ? undefined : tag;
}
function writePointer(cacheHome, project, version, tag) {
  const path = pointerPath(cacheHome, project, version);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, `${tag}
`);
}
function ready(project, version, tag, path, cached) {
  return { kind: "ready", project, version, tag, path, index: join2(path, "_index.md"), cached };
}
function unavailable(project, version, reason, suggestion) {
  return suggestion === undefined ? { kind: "unavailable", project, version, reason } : { kind: "unavailable", project, version, reason, suggestion };
}
async function fetchText(fetchImpl, url) {
  try {
    const response = await fetchImpl(url);
    if (!response.ok)
      return { error: `GET ${url} \u2192 ${response.status}` };
    return await response.text();
  } catch (err) {
    return { error: `GET ${url} failed: ${err instanceof Error ? err.message : String(err)}` };
  }
}
function unpack(archive, project, version, target) {
  mkdirSync(dirname(target), { recursive: true });
  const staging = mkdtempSync(`${target}.staging-`);
  try {
    const archivePath = join2(staging, archiveName(project, version));
    writeFileSync(archivePath, archive);
    const result = spawnSync("tar", ["-xzf", archivePath, "-C", staging], { encoding: "utf8" });
    if (result.error)
      throw new Error(`could not run tar: ${result.error.message}`);
    if (result.status !== 0)
      throw new Error(`tar exited ${result.status}: ${(result.stderr ?? "").trim()}`);
    const extracted = join2(staging, `${project}-${version}`);
    if (!existsSync(extracted))
      throw new Error(`archive does not contain ${project}-${version}/`);
    if (existsSync(target))
      rmSync(target, { recursive: true, force: true });
    renameSync(extracted, target);
  } finally {
    rmSync(staging, { recursive: true, force: true });
  }
}
async function resolveDocs(options) {
  const { project, version, refresh = false, noFetch = false } = options;
  const fetchImpl = options.fetchImpl ?? ((url) => fetch(url));
  const cacheHome = cacheHomeOf(options.cacheHome);
  if (noFetch) {
    const tag = readPointer(cacheHome, project, version);
    const path = tag === undefined ? undefined : docsCachePath(cacheHome, tag);
    if (tag === undefined || path === undefined || !existsSync(path)) {
      return unavailable(project, version, `${project} ${version} is not in the local cache`, "drop --no-fetch to download it");
    }
    return ready(project, version, tag, path, true);
  }
  const catalogText = await fetchText(fetchImpl, CATALOG_URL);
  if (typeof catalogText !== "string")
    return unavailable(project, version, catalogText.error, "check network access to raw.githubusercontent.com");
  let catalog;
  try {
    catalog = JSON.parse(catalogText);
  } catch (err) {
    return unavailable(project, version, `catalog.json is not valid JSON: ${err instanceof Error ? err.message : String(err)}`);
  }
  const lookup = lookupTag(catalog, project, version);
  switch (lookup.kind) {
    case "schema":
      return unavailable(project, version, `catalog.json is schema version ${lookup.found}, this plugin understands 1`, "update the plugin");
    case "unknown-project":
      return unavailable(project, version, `${DOCS_REPO} publishes no project "${project}"`, `known projects: ${lookup.known.join(", ") || "none"}`);
    case "unknown-version":
      return unavailable(project, version, `${DOCS_REPO} has not published ${project} ${version}`, `open an issue at https://github.com/${DOCS_REPO}/issues to have it built`);
  }
  const { tag } = lookup;
  const target = docsCachePath(cacheHome, tag);
  if (existsSync(target) && !refresh) {
    writePointer(cacheHome, project, version, tag);
    return ready(project, version, tag, target, true);
  }
  const checksumText = await fetchText(fetchImpl, checksumUrl(tag, project, version));
  if (typeof checksumText !== "string")
    return unavailable(project, version, checksumText.error);
  const expected = parseChecksum(checksumText, archiveName(project, version));
  if (expected === undefined) {
    return unavailable(project, version, `the checksum published for ${tag} does not describe ${archiveName(project, version)}`);
  }
  let archive;
  try {
    const response = await fetchImpl(archiveUrl(tag, project, version));
    if (!response.ok)
      return unavailable(project, version, `GET ${archiveUrl(tag, project, version)} \u2192 ${response.status}`);
    archive = Buffer.from(await response.arrayBuffer());
  } catch (err) {
    return unavailable(project, version, `downloading ${tag} failed: ${err instanceof Error ? err.message : String(err)}`);
  }
  const actual = createHash("sha256").update(archive).digest("hex");
  if (actual !== expected) {
    return unavailable(project, version, `checksum mismatch for ${tag}: expected ${expected.slice(0, 12)}\u2026, got ${actual.slice(0, 12)}\u2026`, "nothing was written to the cache; retry, and report it if it persists");
  }
  try {
    unpack(archive, project, version, target);
  } catch (err) {
    return unavailable(project, version, `unpacking ${tag} failed: ${err instanceof Error ? err.message : String(err)}`);
  }
  writePointer(cacheHome, project, version, tag);
  return ready(project, version, tag, target, false);
}
var USAGE = "usage: bun run scripts/docs.ts <project> <version> [--refresh] [--no-fetch]";
function parseArgs(argv) {
  const positional = [];
  let refresh = false;
  let noFetch = false;
  for (const arg of argv) {
    if (arg === "--refresh")
      refresh = true;
    else if (arg === "--no-fetch")
      noFetch = true;
    else if (arg.startsWith("--"))
      return { error: `unknown argument: ${arg}` };
    else
      positional.push(arg);
  }
  const [project, version, ...extra] = positional;
  if (!project)
    return { error: "missing <project>" };
  if (!version)
    return { error: "missing <version>" };
  if (extra.length > 0)
    return { error: `unexpected argument: ${extra[0]}` };
  return { project, version, refresh, noFetch };
}
async function cli(argv) {
  const parsed = parseArgs(argv);
  if ("error" in parsed) {
    process.stderr.write(`${parsed.error}
${USAGE}
`);
    return 2;
  }
  let result;
  try {
    result = await resolveDocs(parsed);
  } catch (err) {
    process.stderr.write(`${err instanceof Error ? err.stack ?? err.message : String(err)}
`);
    return 2;
  }
  process.stdout.write(`${JSON.stringify(result, null, 2)}
`);
  return result.kind === "ready" ? 0 : 1;
}
if (true) {
  const code = await cli(process.argv.slice(2));
  process.exit(code);
}
export {
  parseArgs,
  resolveDocs
};
