#!/usr/bin/env bun
/**
 * Bundles the domain scripts into `skills/spring-docs/scripts/` — Build step.
 *
 * The skill ships through two channels with different guarantees. As a Claude
 * Code plugin it gets `${CLAUDE_PLUGIN_ROOT}` and an automatic
 * `bun install --frozen-lockfile` of the root `package.json`. Installed
 * standalone with `npx skills`, it gets neither: only the skill directory is
 * copied, so nothing above it exists and no dependency install runs.
 *
 * Bundling to dependency-free files inside the skill directory is what makes
 * the second channel work. The output is committed because `npx skills` copies
 * straight from the repository — no build step runs between the two.
 *
 * Usage:
 *   bun run build:skill          # write the bundles
 *   bun run build:skill --check  # fail if the committed bundles are stale
 */

import { existsSync, readFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import process from 'node:process'

const ENTRYPOINTS = ['scripts/docs.ts', 'scripts/detect.ts']
const OUTDIR = 'skills/spring-docs/scripts'
/**
 * Extension of the bundles.
 *
 * `.mjs`, not `.js`: the output is ESM and the skill directory carries no
 * `package.json` to declare that, so a `.js` bundle is a CommonJS file to every
 * Node that does not detect module syntax on its own — unflagged only since
 * 22.7. There it dies on the first `import` before resolving any docs, and the
 * standalone install channel is exactly where no `package.json` can be added.
 */
const EXT = '.mjs'
/** The entrypoint's own `#!/usr/bin/env bun` line, replaced by the node one. */
const SHEBANG = /^#![^\n]*\n/

/** Shebang plus a do-not-edit banner, replacing the entrypoint's own shebang. */
function header(entrypoint: string): string {
  return [
    '#!/usr/bin/env node',
    `// Generated by \`bun run build:skill\` from ${entrypoint} — do not edit.`,
    '// Regenerate and commit after changing anything under scripts/.',
    '',
  ].join('\n')
}

/** Bundle one entrypoint and return its final contents. */
async function bundle(entrypoint: string): Promise<string> {
  const built = await Bun.build({
    entrypoints: [entrypoint],
    target: 'node',
    // The bundle runs from the user's skill directory, where no `node_modules`
    // exists, so every non-builtin import has to be inlined.
    packages: 'bundle',
    define: {
      // Bun lowers `import.meta.main` to a `__require` comparison that only
      // resolves when some dependency happens to pull in the CJS interop
      // helper, so under plain node the guard throws ReferenceError in one
      // bundle and works by accident in another. A bundle is always run as the
      // entrypoint, so the guard is constant here.
      'import.meta.main': 'true',
    },
  })
  if (!built.success)
    throw new AggregateError(built.logs, `bundling ${entrypoint} failed`)

  const [artifact] = built.outputs
  if (!artifact)
    throw new Error(`bundling ${entrypoint} produced no output`)

  const code = await artifact.text()
  return header(entrypoint) + code.replace(SHEBANG, '')
}

async function main(argv: string[]): Promise<number> {
  const check = argv.includes('--check')
  const stale: string[] = []

  for (const entrypoint of ENTRYPOINTS) {
    const outfile = join(OUTDIR, `${basename(entrypoint, '.ts')}${EXT}`)
    const contents = await bundle(entrypoint)

    if (check) {
      const current = existsSync(outfile) ? readFileSync(outfile, 'utf8') : ''
      if (current !== contents)
        stale.push(outfile)
      continue
    }

    await Bun.write(outfile, contents)
    process.stdout.write(`${outfile}  ${(contents.length / 1024).toFixed(1)} KB\n`)
  }

  if (stale.length > 0) {
    process.stderr.write(
      `Committed bundles are stale: ${stale.join(', ')}\n`
      + 'Run `bun run build:skill` and commit the result.\n',
    )
    return 1
  }

  return 0
}

if (import.meta.main) {
  const code = await main(process.argv.slice(2))
  process.exit(code)
}
